# This is a basic workflow to help you get started with Actions
name: Connect to an AWS role from a GitHub repository
# on:
#   push: 
#     tags:
#       - '*.*.*'

# Controls when the action will run. Invokes the workflow on push events but only for the main branch
# on:
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]

# on: 
#   workflow_dispatch:
#     branches: [ naisha-onboarding ] 

on:
  push:
    branches: [ naisha-onboarding ]
  pull_request:
    branches: [ naisha-onboarding ]
  workflow_dispatch:


env:
  AWS_REGION : "ap-southeast-1" #Change to reflect your Region

# Permission can be added at job level or workflow level    
permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout
jobs:
  # CallReusableWorkflow:
  #   uses: ./.github/workflows/reusable-workflow.yml

  TestManualApprovers:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.ACTIONS_PAT }}
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4
      - name: Test manual Approvers
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: ${{ github.actor }}
          minimum-approvals: 1
          issue-title: "Deploying v1.3.5 to prod from staging"
          issue-body: "Please approve or deny the deployment of version v1.3.5."
          exclude-workflow-initiator-as-approver: false
          additional-approved-words: ''
          additional-denied-words: ''

      # - name: Create Release
      #   id: create_release
      #   uses: actions/create-release@v1
      #   with:
      #     tag_name: test
      #     release_name: Release test
      #     body: |
      #       Test Release
      #     draft: false
      #     prerelease: false
      # - name: configure aws credentials
      #   uses: aws-actions/configure-aws-credentials@v4
      #   with:
      #     role-to-assume: ${{ secrets.SERVICE_ACCOUNT_ROLE }} #change to reflect your IAM role’s ARN
      #     role-session-name: GitHub_to_AWS_via_FederatedOIDC
      #     aws-region: ${{ env.AWS_REGION }}
      # # Hello from AWS: WhoAmI
      # - name: Sts GetCallerIdentity
      #   run: |
      #     aws sts get-caller-identity
  # Creating-Release:
  #   runs-on: ubuntu-latest
  #   env:
  #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #   steps:
  #     - name: Create Release
  #       id: create_release
  #       uses: actions/create-release@v1
  #       with:
  #         tag_name: ${{ github.ref }}
  #         release_name: Release ${{ github.ref }}
  #         body: |
  #           Test Release
  #         draft: false
  #         prerelease: false
    
